# fly.toml app configuration file generated for langguin on 2024-09-16T21:15:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langguin'
primary_region = 'jnb'

[processes]
web = "npm --prefix app/ run start"
server = "/server/.venv/bin/fastapi run /server/server"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
